In [1]:
import pandas as pd
import torch

In [5]:
a = torch.randn(3,10,2)
print(a.shape)
a

torch.Size([3, 10, 2])


tensor([[[ 0.7274,  1.1090],
         [ 1.5758,  1.2963],
         [ 0.4925, -0.7227],
         [-1.3617, -0.0141],
         [ 0.5592,  0.3923],
         [-0.9354, -0.1629],
         [ 0.8798, -0.7055],
         [-0.7422,  0.1480],
         [-1.0169,  1.4347],
         [-0.8847, -0.6141]],

        [[-1.4663, -0.9447],
         [ 0.9291,  1.8346],
         [ 1.7019, -1.0503],
         [-0.8422, -0.3219],
         [-1.3486,  0.0946],
         [ 0.1569,  1.6361],
         [-0.1627, -0.2741],
         [-1.1794, -0.5699],
         [-0.5885, -0.4612],
         [-0.5048,  0.4766]],

        [[ 0.2969, -1.0112],
         [-0.0256, -1.5108],
         [ 1.9946,  1.7809],
         [-0.4144, -0.5957],
         [ 0.1216, -0.4701],
         [-0.2138,  1.6508],
         [-1.4852,  1.3161],
         [-0.2173, -0.6043],
         [-0.4651,  0.5505],
         [-1.0631,  1.0039]]])

In [26]:
import numpy as np
img = np.array([[[1,2], [3, 4], [5,6], [7,8]]])
print(img)
print(len(img.shape))
# img = img[:, :, 0] if len(img.shape) == 3 else img
if len(img.shape) == 3:
   img = img[:, :, 0]
else:
    img = img

print(img)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3
[[1 3 5 7]]


In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv('./data/ETT/xixia_ms.csv')
data.head()
